"use client";

import React, { useEffect, useState } from "react";
import { Printer, ArrowLeft, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { Verdict, Evidence, Extraction, OfficialChannel } from "@/lib/types";

interface ReportPayload {
  timestamp: string;
  verdict: Verdict;
  evidences: Evidence[];
  extraction: Extraction;
  inputText: string;
  officialChannel?: OfficialChannel;
}

export default function ReportPage() {
  const [data, setData] = useState<ReportPayload | null>(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const stored = sessionStorage.getItem("callback_report_data");
      if (stored) {
        try {
          setData(JSON.parse(stored));
        } catch {
          // ignore parse error
        }
      }
    }
  }, []);

  const handlePrint = () => {
    if (typeof window !== "undefined") {
      window.print();
    }
  };

  if (!data) {
    return (
      <div className="min-h-screen p-8 text-center space-y-4">
        <p className="text-slate-500">No report data found. Please run a check first on Callback.</p>
        <Link href="/" className="inline-flex items-center gap-1.5 text-brand-600 text-sm font-semibold">
          <ArrowLeft className="w-4 h-4" /> Return to Homepage
        </Link>
      </div>
    );
  }

  const { verdict, evidences, extraction, inputText, officialChannel, timestamp } = data;

  return (
    <div className="max-w-3xl mx-auto p-6 md:p-12 font-sans bg-white text-slate-900 min-h-screen">
      {/* Top action bar (hidden in print) */}
      <div className="no-print flex items-center justify-between pb-6 mb-8 border-b border-slate-200">
        <Link href="/" className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-600 hover:text-slate-900">
          <ArrowLeft className="w-4 h-4" /> Back to Callback
        </Link>
        <button
          onClick={handlePrint}
          className="inline-flex items-center gap-1.5 px-4 py-2 bg-brand-600 text-white rounded-lg text-xs font-semibold hover:bg-brand-700 transition"
        >
          <Printer className="w-4 h-4" /> Print / Save as PDF
        </button>
      </div>

      {/* Header */}
      <div className="border-b-2 border-slate-900 pb-4 mb-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-black tracking-tight text-slate-900">
              CALLBACK INCIDENT REPORT
            </h1>
            <p className="text-xs text-slate-500 font-mono mt-0.5">
              Consumer Phishing & Imposter Verification Summary · ForgeHacks 2026
            </p>
          </div>
          <div className="text-right text-xs font-mono text-slate-500">
            <div>Date: {timestamp}</div>
            <div>Status: VERIFIED</div>
          </div>
        </div>
      </div>

      {/* Notice */}
      <div className="p-3 mb-6 bg-slate-50 border border-slate-200 text-xs text-slate-600 rounded">
        <strong>Notice:</strong> This document is generated by Callback as a reference summary to help you file an incident report with consumer protection agencies (such as ReportFraud.ftc.gov or ic3.gov). It is not a formal law enforcement chain of custody or legal affidavit.
      </div>

      {/* 1. Verdict */}
      <div className="mb-6 space-y-1">
        <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400">
          1. Verification Outcome
        </h2>
        <div className="p-3 bg-slate-100 rounded border border-slate-300 font-mono text-sm">
          <div className="font-bold text-base text-slate-900">{verdict.headline}</div>
          <div className="text-xs text-slate-600 mt-1">Rule ID: {verdict.rule_id}</div>
          <div className="text-xs text-slate-700 mt-1">{verdict.details}</div>
        </div>
      </div>

      {/* 2. Sender & Contacts */}
      <div className="mb-6 space-y-2">
        <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400">
          2. Extracted Message Details
        </h2>
        <table className="w-full text-xs border border-slate-200 divide-y divide-slate-200">
          <tbody>
            <tr>
              <td className="p-2 font-semibold bg-slate-50 w-44">Claimed Sender:</td>
              <td className="p-2 font-mono">{extraction.claimed_sender.name || "Unknown"} ({extraction.claimed_sender.kind})</td>
            </tr>
            <tr>
              <td className="p-2 font-semibold bg-slate-50">Evidence Quote:</td>
              <td className="p-2 font-mono">&quot;{extraction.claimed_sender.evidence_quote || "N/A"}&quot;</td>
            </tr>
            <tr>
              <td className="p-2 font-semibold bg-slate-50">Phone Numbers:</td>
              <td className="p-2 font-mono">{extraction.phones.length > 0 ? extraction.phones.join(", ") : "None"}</td>
            </tr>
            <tr>
              <td className="p-2 font-semibold bg-slate-50">Links & Domains:</td>
              <td className="p-2 font-mono">{extraction.urls.length > 0 ? extraction.urls.join(", ") : "None"}</td>
            </tr>
            <tr>
              <td className="p-2 font-semibold bg-slate-50">Emails:</td>
              <td className="p-2 font-mono">{extraction.emails.length > 0 ? extraction.emails.join(", ") : "None"}</td>
            </tr>
            {extraction.payment.method && (
              <tr>
                <td className="p-2 font-semibold bg-slate-50">Payment Demanded:</td>
                <td className="p-2 font-mono">{extraction.payment.method} (&quot;{extraction.payment.quote}&quot;)</td>
              </tr>
            )}
            {extraction.urgency_quotes.length > 0 && (
              <tr>
                <td className="p-2 font-semibold bg-slate-50">Urgency Phrases:</td>
                <td className="p-2 font-mono">{extraction.urgency_quotes.join("; ")}</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* 3. Official Channels */}
      {officialChannel && (
        <div className="mb-6 space-y-2">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400">
            3. Verified Official Channels (Public Records)
          </h2>
          <table className="w-full text-xs border border-slate-200 divide-y divide-slate-200">
            <tbody>
              <tr>
                <td className="p-2 font-semibold bg-slate-50 w-44">Official Organization:</td>
                <td className="p-2 font-mono">{officialChannel.name}</td>
              </tr>
              <tr>
                <td className="p-2 font-semibold bg-slate-50">Official Domain:</td>
                <td className="p-2 font-mono">{officialChannel.domain || "N/A"}</td>
              </tr>
              <tr>
                <td className="p-2 font-semibold bg-slate-50">Official Website URL:</td>
                <td className="p-2 font-mono truncate">{officialChannel.contact_url || "N/A"}</td>
              </tr>
              <tr>
                <td className="p-2 font-semibold bg-slate-50">Official Support Phone:</td>
                <td className="p-2 font-mono">{officialChannel.phone || "N/A"}</td>
              </tr>
              <tr>
                <td className="p-2 font-semibold bg-slate-50">Grounding Source:</td>
                <td className="p-2 font-mono">{officialChannel.source_note || "Wikidata P856 & Official Contact Pages"}</td>
              </tr>
            </tbody>
          </table>
        </div>
      )}

      {/* 4. Evidence Receipts */}
      <div className="mb-6 space-y-2">
        <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400">
          4. Evidence Receipts & Findings
        </h2>
        <div className="space-y-1.5 font-mono text-xs">
          {evidences.map((e) => (
            <div key={e.id} className="p-2 border border-slate-200 rounded">
              <span className="font-bold text-brand-700">[{e.id}]</span> [{e.kind.toUpperCase()} - {e.status.toUpperCase()}]: {e.text}
            </div>
          ))}
        </div>
      </div>

      {/* 5. Reporting Guidance */}
      <div className="mb-6 p-4 bg-slate-50 border border-slate-200 rounded space-y-2 text-xs">
        <h2 className="font-bold text-slate-800">5. Where to Submit This Incident Report</h2>
        <ul className="list-disc pl-4 space-y-1 text-slate-600">
          <li><strong>Federal Trade Commission (FTC):</strong> Visit <code>ReportFraud.ftc.gov</code> and paste the sender details, phone/link, and payment ask.</li>
          <li><strong>FBI IC3:</strong> For financial fraud, visit <code>ic3.gov</code> and file an Internet Crime complaint.</li>
          <li><strong>SMS Smishing:</strong> Forward the text message directly to <strong>7726</strong> (SPAM) on your mobile carrier.</li>
        </ul>
      </div>

      {/* 6. Original Message */}
      <div className="space-y-1">
        <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400">
          6. Original Message Text
        </h2>
        <pre className="p-3 bg-slate-100 rounded text-xs font-mono whitespace-pre-wrap border border-slate-200 text-slate-800">
          {inputText}
        </pre>
      </div>

      {/* Footer */}
      <div className="mt-8 pt-4 border-t border-slate-200 text-center font-mono text-[10px] text-slate-400">
        Generated by Callback · ForgeHacks Online 2026 · Built with an AI coding assistant & the review pass
      </div>
    </div>
  );
}
